// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.jingoal.grpc.helloworld;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloWorldReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloWorldReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloWorldResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloWorldResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020helloworld.proto\022\nhelloworld\"\035\n\rHelloW" +
      "orldReq\022\014\n\004name\030\001 \001(\t\"!\n\016HelloWorldResp\022" +
      "\017\n\007message\030\001 \001(\t2\230\001\n\007Greeter\022C\n\010SayHello" +
      "\022\031.helloworld.HelloWorldReq\032\032.helloworld" +
      ".HelloWorldResp\"\000\022H\n\rSayHelloAgain\022\031.hel" +
      "loworld.HelloWorldReq\032\032.helloworld.Hello" +
      "WorldResp\"\000B6\n\033com.jingoal.grpc.hellowor" +
      "ldB\017HelloWorldProtoP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_helloworld_HelloWorldReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_HelloWorldReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloWorldReq_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_helloworld_HelloWorldResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_HelloWorldResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloWorldResp_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
